import{cleanup,render,screen,within}from'@testing-library/react';
import userEvent from'@testing-library/user-event';
import{afterEach,beforeEach,describe,expect,it}from'vitest';
import App from'./App';
import{deriveServices,type Route}from'./model';
import{routes}from'./mock';

afterEach(()=>{cleanup();history.replaceState({},'',location.pathname)});
beforeEach(()=>history.replaceState({},'',location.pathname+'?scenario=mock'));
const clone=(route:Route,changes:Partial<Route>):Route=>({...route,...changes});

describe('independent review regressions',()=>{
 it('keys services by scheme, host, and port',()=>{const https=clone(routes[0],{id:'https',domain:'secure.example.com',target:{...routes[0].target,scheme:'https'}});expect(deriveServices([routes[0],https])).toHaveLength(2);expect(deriveServices([routes[0],https]).map(s=>s.address)).toEqual(expect.arrayContaining(['http://192.0.2.20:3000','https://192.0.2.20:3000']))});
 it('aggregates worst service health independent of route order',()=>{const healthy=routes[0],degraded=clone(routes[1],{target:healthy.target}),offline=clone(routes[2],{target:healthy.target});expect(deriveServices([offline,healthy,degraded])[0].health).toBe('offline');expect(deriveServices([healthy,offline,degraded])[0].health).toBe('offline');expect(deriveServices([degraded,healthy])[0].health).toBe('degraded');expect(deriveServices([healthy,degraded])[0].health).toBe('degraded')});
 it('saves partial success with truthful component states',async()=>{history.replaceState({},'','?scenario=partial');render(<App/>);await userEvent.click(screen.getByRole('button',{name:'Proxy Routes'}));await userEvent.click(screen.getByRole('button',{name:'Add route'}));await userEvent.type(screen.getByLabelText('Domain'),'new.example.com');await userEvent.type(screen.getAllByRole('textbox')[1],'192.0.2.55');await userEvent.click(screen.getByRole('button',{name:'Save route'}));expect(await screen.findByText('partial success')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'View Proxy'}));const row=screen.getByText('new.example.com').closest('tr')!;expect(within(row).getByText('Apply failed')).toBeInTheDocument();expect(within(row).getByText('Unknown')).toBeInTheDocument();expect(within(row).getByText('Resolved')).toBeInTheDocument();expect(within(row).getByText('Pending')).toBeInTheDocument()});
 it('empty scenario empties DNS and certificates with specific states',async()=>{history.replaceState({},'','?scenario=empty');render(<App/>);await userEvent.click(screen.getByRole('button',{name:'DNS Records'}));expect(screen.getByRole('heading',{name:'No DNS records'})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Certificates'}));expect(screen.getByRole('heading',{name:'No certificates'})).toBeInTheDocument()});
 it('removes managed DNS only when delete checkbox is checked',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'Proxy Routes'}));await userEvent.click(screen.getByLabelText('Delete grafana.example.com'));await userEvent.click(screen.getByRole('button',{name:'Delete route'}));await userEvent.click(screen.getByRole('button',{name:'DNS Records'}));expect(screen.queryByText('grafana.example.com')).not.toBeInTheDocument()});
 it('preserves managed DNS when delete checkbox is unchecked',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'Proxy Routes'}));await userEvent.click(screen.getByLabelText('Delete grafana.example.com'));await userEvent.click(screen.getByLabelText('Remove managed DNS record'));await userEvent.click(screen.getByRole('button',{name:'Delete route'}));await userEvent.click(screen.getByRole('button',{name:'DNS Records'}));expect(screen.getByText('grafana.example.com')).toBeInTheDocument()});
 it('opens route detail with a semantic keyboard-operable control',async()=>{render(<App/>);await userEvent.click(screen.getByRole('button',{name:'Proxy Routes'}));const control=screen.getByRole('button',{name:'View grafana.example.com'});control.focus();await userEvent.keyboard('{Enter}');expect(screen.getByRole('heading',{name:/grafana.example.com/})).toBeInTheDocument()});
});
